"""Project status reporting agent.

Reads a project's own files (digest), understands its state, and produces
a ProjectStatus: a short headline + health for the UI column and a full
markdown report destined for <project>/project_status.md.

Tier 0 is deterministic and always available. Tier 1 (LangGraph over any
OpenAI-compatible endpoint) adds a narrative summary and next steps.
"""

import os
import subprocess
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from dcp.agents.base import Agent, AgentResult, AgentUnavailable
from dcp.config import Settings

GENERATED_MARKER = "<!-- generated by Developer Control Plane -->"

# Files worth quoting to an LLM, in priority order.
_MANIFESTS = (
    "package.json", "pyproject.toml", "requirements.txt", "setup.py",
    "Cargo.toml", "go.mod", "pom.xml", "build.gradle", "composer.json",
    "Gemfile", "pubspec.yaml", "mix.exs",
)
_README_NAMES = ("README.md", "README.rst", "README.txt", "readme.md")

_CAP_README = 2000
_CAP_MANIFEST = 1500
_CAP_TREE_ENTRIES = 60


class ProjectStatus(BaseModel):
    path: str
    headline: str = Field(max_length=120)
    health: str = "yellow"  # green | yellow | red
    summary: str = ""
    next_steps: List[str] = Field(default_factory=list)
    generated_at: str = Field(default_factory=lambda: datetime.now().isoformat())
    tier: int = 0

    def to_markdown(self) -> str:
        lines = [
            GENERATED_MARKER,
            f"# Project Status: {os.path.basename(self.path) or self.path}",
            "",
            f"**Health:** {self.health}  ",
            f"**Status:** {self.headline}  ",
            f"**Generated:** {self.generated_at} "
            f"(tier {self.tier}{', deterministic' if self.tier == 0 else ', AI'})",
            "",
            "## Summary",
            self.summary or "_no summary_",
        ]
        if self.next_steps:
            lines += ["", "## Suggested next steps"]
            lines += [f"- {step}" for step in self.next_steps]
        lines += ["", "---", f"_Path: `{self.path}`_", ""]
        return "\n".join(lines)


def collect_project_digest(path: str) -> str:
    """Small, size-capped textual digest of a project for LLM consumption."""
    parts: List[str] = []

    for name in _README_NAMES:
        readme = os.path.join(path, name)
        if os.path.isfile(readme):
            parts.append(f"## {name} (head)\n" + _read_head(readme, _CAP_README))
            break

    for name in _MANIFESTS:
        manifest = os.path.join(path, name)
        if os.path.isfile(manifest):
            parts.append(f"## {name}\n" + _read_head(manifest, _CAP_MANIFEST))
            break

    tree = _file_tree(path, max_entries=_CAP_TREE_ENTRIES)
    if tree:
        parts.append("## File tree (partial)\n" + "\n".join(tree))

    git_log = _recent_git_log(path)
    if git_log:
        parts.append("## Recent commits\n" + git_log)

    return "\n\n".join(parts)


def _read_head(file_path: str, cap: int) -> str:
    try:
        with open(file_path, "r", encoding="utf-8", errors="replace") as fh:
            return fh.read(cap)
    except OSError:
        return "(unreadable)"


def _file_tree(path: str, max_entries: int) -> List[str]:
    entries: List[str] = []
    try:
        for name in sorted(os.listdir(path)):
            if name.startswith(".") or name in ("node_modules", "__pycache__",
                                                "venv", ".venv"):
                continue
            full = os.path.join(path, name)
            entries.append(name + ("/" if os.path.isdir(full) else ""))
            if os.path.isdir(full):
                try:
                    for child in sorted(os.listdir(full))[:8]:
                        entries.append(f"  {name}/{child}")
                        if len(entries) >= max_entries:
                            return entries
                except OSError:
                    continue
            if len(entries) >= max_entries:
                break
    except OSError:
        pass
    return entries


def _recent_git_log(path: str) -> str:
    if not os.path.isdir(os.path.join(path, ".git")):
        return ""
    try:
        res = subprocess.run(
            ["git", "-C", path, "log", "-10", "--format=%cs %s"],
            capture_output=True, text=True, timeout=5, check=False,
        )
        return res.stdout.strip() if res.returncode == 0 else ""
    except (OSError, subprocess.TimeoutExpired):
        return ""


def build_tier0_status(context: Dict[str, Any]) -> ProjectStatus:
    """Deterministic status from genome + stage — no AI involved."""
    path = context["project"]
    genome = context.get("genome", {})
    stage = context.get("stage") or {}
    git = genome.get("git", {})

    findings: List[str] = []
    next_steps: List[str] = []
    score = 0

    if git.get("is_repo"):
        score += 1
        if git.get("dirty_files", 0) > 10:
            findings.append(f"{git['dirty_files']} uncommitted files")
            next_steps.append("Commit or stash pending changes")
    else:
        findings.append("no git")
        next_steps.append("Initialize version control")
    if genome.get("has_tests"):
        score += 1
    else:
        findings.append("no tests")
        next_steps.append("Add a test suite")
    if genome.get("has_ci"):
        score += 1
    else:
        next_steps.append("Add CI")
    if genome.get("has_docs"):
        score += 1
    else:
        findings.append("no docs")

    health = "green" if score >= 3 else ("yellow" if score == 2 else "red")
    stage_txt = stage.get("stage", "?")
    conf = stage.get("confidence", 0.0)
    headline_bits = [genome.get("type", "Unknown"), f"{stage_txt} ({conf:.0%})"]
    if findings:
        headline_bits.append(", ".join(findings[:2]))
    headline = " · ".join(headline_bits)[:120]

    summary_lines = [
        f"Detected stack: **{genome.get('type', 'Unknown')}**; "
        f"inferred stage **{stage_txt}** at {conf:.0%} confidence.",
    ]
    for ev in (stage.get("evidence") or [])[:6]:
        summary_lines.append(f"- {ev}")

    return ProjectStatus(
        path=path, headline=headline, health=health,
        summary="\n".join(summary_lines), next_steps=next_steps, tier=0,
    )


class StatusReportAgent(Agent):
    name = "status-report"
    tier = 1
    description = (
        "Reads project files and produces project_status.md "
        "(LangGraph when AI is enabled, deterministic otherwise)."
    )

    def __init__(self, settings: Settings):
        self.settings = settings

    # The router treats AgentUnavailable as "fall back to tier 0", but this
    # agent handles its own fallback so batch analysis never needs a second
    # agent: run() always returns a usable ProjectStatus.
    def build_status(self, context: Dict[str, Any]) -> ProjectStatus:
        try:
            return self._tier1_status(context)
        except AgentUnavailable:
            return build_tier0_status(context)

    def run(self, context: Dict[str, Any]) -> AgentResult:
        status = self.build_status(context)
        return AgentResult(
            agent=self.name,
            summary=status.headline,
            recommendations=status.next_steps,
            notes=[f"health={status.health}", f"tier={status.tier}"],
        )

    def _tier1_status(self, context: Dict[str, Any]) -> ProjectStatus:
        if not self.settings.ai_enabled:
            raise AgentUnavailable("AI tier disabled")
        if not (self.settings.llm_api_key and self.settings.llm_model):
            raise AgentUnavailable("LLM credentials missing")
        try:
            from langchain_openai import ChatOpenAI
        except ImportError as exc:
            raise AgentUnavailable("langchain-openai not installed") from exc

        kwargs: Dict[str, Any] = {
            "model": self.settings.llm_model,
            "api_key": self.settings.llm_api_key,
            "temperature": 0.2,
        }
        if self.settings.llm_api_base:
            kwargs["base_url"] = self.settings.llm_api_base
        llm = ChatOpenAI(**kwargs)

        path = context["project"]
        digest = collect_project_digest(path)
        base = build_tier0_status(context)  # deterministic facts as anchor

        prompt = (
            "You are a principal engineer reviewing a local project.\n"
            f"Deterministic facts: {base.headline}\n\n"
            f"{digest}\n\n"
            "Reply in EXACTLY this format:\n"
            "HEADLINE: <one line, max 90 chars, project state in plain words>\n"
            "HEALTH: <green|yellow|red>\n"
            "SUMMARY: <2-4 sentences on purpose, state, and completeness>\n"
            "NEXT: <step 1>\n"
            "NEXT: <step 2>\n"
            "NEXT: <step 3>"
        )
        reply = llm.invoke(prompt).content

        headline, health, summary, steps = base.headline, base.health, "", []
        for line in reply.splitlines():
            stripped = line.strip()
            if stripped.upper().startswith("HEADLINE:"):
                headline = stripped[9:].strip()[:120] or headline
            elif stripped.upper().startswith("HEALTH:"):
                value = stripped[7:].strip().lower()
                if value in ("green", "yellow", "red"):
                    health = value
            elif stripped.upper().startswith("SUMMARY:"):
                summary = stripped[8:].strip()
            elif stripped.upper().startswith("NEXT:"):
                step = stripped[5:].strip()
                if step:
                    steps.append(step)

        return ProjectStatus(
            path=path, headline=headline, health=health,
            summary=summary or base.summary,
            next_steps=steps or base.next_steps, tier=1,
        )
