"""Self-improvement pipeline for the Developer Control Plane itself.

Bottlenecks observed while agents work on other projects (run failures,
timeouts, guard skips, analysis errors) become tasks in a dedicated
``self`` pipeline. They are mirrored to a human-readable
``self_improvement.md`` at the control plane's root and surfaced in the
UI. A background loop checks daily and executes AT MOST ONE
self-improvement task per day — and only when no other project's work
is pending or in progress (other projects always come first).
"""

import logging
import os
import threading
from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from dcp.agents.executor import CodeAgentExecutor
from dcp.core.models import AgentRun, Task
from dcp.cortex.tasks import TaskService
from dcp.database import EventSourcingDB

logger = logging.getLogger(__name__)

SELF_FILE = "self_improvement.md"
CHECK_INTERVAL_SECONDS = 3600  # hourly check, daily execution


class SelfImprovementManager:
    def __init__(
        self,
        db: EventSourcingDB,
        tasks: TaskService,
        executor: CodeAgentExecutor,
        home_path: str,
    ):
        """home_path: the developer plane's own repository root."""
        self.db = db
        self.tasks = tasks
        self.executor = executor
        self.home_path = os.path.abspath(home_path)
        self._lock = threading.Lock()
        self._stop = threading.Event()
        self._thread: Optional[threading.Thread] = None
        self._last_result: Optional[Dict[str, Any]] = None

    # ------------------------------------------------------------ bottlenecks
    def record_bottleneck(self, kind: str, detail: str,
                          project_id: Optional[str] = None) -> Optional[Task]:
        """Turn an observed bottleneck into a self-improvement task."""
        title = f"[{kind}] {detail}"[:200]
        created = self.tasks.seed(
            self.home_path, [title], origin=f"bottleneck:{project_id or 'system'}",
            pipeline="self", detail=detail,
        )
        self.db.log_signal(
            "BottleneckObserved",
            {"kind": kind, "detail": detail[:500], "source_project": project_id},
            project_id=self.home_path,
        )
        self.write_self_file()
        return created[0] if created else None

    # ------------------------------------------------------------- self file
    def write_self_file(self) -> str:
        """Mirror the self pipeline into self_improvement.md (committed doc)."""
        tasks = self.db.list_tasks(pipeline="self", limit=500)
        by_status: Dict[str, List[Task]] = {}
        for task in tasks:
            by_status.setdefault(task.status, []).append(task)

        lines = [
            "<!-- generated by Developer Control Plane — self-improvement pipeline -->",
            "# Self-Improvement Backlog",
            "",
            "Bottlenecks observed while agents worked on other projects.",
            "One task is executed per day, and only when no other project's",
            "work is pending or in progress.",
            "",
        ]
        for status in ("in_progress", "review", "todo", "done", "discarded"):
            items = by_status.get(status, [])
            if not items:
                continue
            lines.append(f"## {status.replace('_', ' ').title()} ({len(items)})")
            for task in items:
                lines.append(f"- [{task.created_at[:10]}] {task.title}"
                             f" _(from {task.origin})_")
            lines.append("")
        path = os.path.join(self.home_path, SELF_FILE)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines))
        return path

    # ----------------------------------------------------------- daily cycle
    def start_scheduler(self) -> None:
        if self._thread is not None:
            return
        self._thread = threading.Thread(target=self._loop, daemon=True)
        self._thread.start()
        logger.info("Self-improvement scheduler started (hourly check)")

    def stop_scheduler(self) -> None:
        self._stop.set()
        if self._thread is not None:
            self._thread.join(timeout=5)
            self._thread = None

    def _loop(self) -> None:
        while not self._stop.wait(CHECK_INTERVAL_SECONDS):
            try:
                self.maybe_run_daily()
            except Exception:  # noqa: BLE001
                logger.exception("Self-improvement daily check failed")

    def other_work_active(self) -> bool:
        """True when any other project still has open work — they come first."""
        pending_runs = self.db.get_agent_runs(limit=50, pending_only=True)
        if any(r.project_id != self.home_path for r in pending_runs):
            return True
        open_project_tasks = self.db.count_open_tasks(pipeline="project")
        home_open = sum(
            1 for t in self.db.list_tasks(project_id=self.home_path, limit=500)
            if t.pipeline == "project" and t.status in ("todo", "in_progress", "review")
        )
        return (open_project_tasks - home_open) > 0

    def last_execution_at(self) -> Optional[datetime]:
        for decision in self.db.get_decisions(limit=500):
            if decision.decision_type == "SelfImprovementExecuted":
                try:
                    return datetime.fromisoformat(decision.timestamp)
                except ValueError:
                    return None
        return None

    def maybe_run_daily(self, now: Optional[datetime] = None) -> Dict[str, Any]:
        """Execute at most one self task if due and unblocked."""
        now = now or datetime.now()
        with self._lock:
            last = self.last_execution_at()
            if last is not None and now - last < timedelta(days=1):
                return self._skip("daily budget spent", last)
            if self.other_work_active():
                return self._skip("other projects' work still open", last)
            todo = self.tasks.open_tasks(self.home_path, pipeline="self", limit=1)
            if not todo:
                return self._skip("no self-improvement tasks queued", last)
            return self._execute(todo[0])

    def _skip(self, reason: str, last: Optional[datetime]) -> Dict[str, Any]:
        result = {"executed": False, "reason": reason,
                  "last_execution": last.isoformat() if last else None}
        self._last_result = result
        return result

    def _execute(self, task: Task) -> Dict[str, Any]:
        self.tasks.move(task.id, "in_progress", actor="self-improvement")
        brief = (
            f"# Self-improvement task for the Developer Control Plane\n"
            f"Repository: {self.home_path}\n\n"
            f"## Task\n{task.title}\n\n{task.detail}\n\n"
            "## Rules (non-negotiable)\n"
            "- Work ONLY inside this repository.\n"
            "- Do NOT commit, push, or touch .git.\n"
            "- Keep changes minimal and focused on the task.\n"
            "- Update README.md / docs if behavior changes.\n"
            "- Add or update tests for what you change.\n"
        )
        run = self.db.insert_agent_run(
            AgentRun(project_id=self.home_path, task_brief=brief)
        )
        outcome = self.executor.execute(self.home_path, brief)
        self.db.finish_agent_run(
            run.id, outcome.exit_code, outcome.diff_stat, outcome.report
        )
        self.tasks.move(task.id, "review", run_id=run.id, actor="self-improvement")
        self.db.log_decision(
            "SelfImprovementExecuted",
            {"task_id": task.id, "run_id": run.id, "exit_code": outcome.exit_code},
            project_id=self.home_path,
        )
        self.write_self_file()
        result = {"executed": True, "task_id": task.id, "run_id": run.id,
                  "exit_code": outcome.exit_code}
        self._last_result = result
        return result

    # ---------------------------------------------------------------- status
    def status(self) -> Dict[str, Any]:
        last = self.last_execution_at()
        return {
            "home": self.home_path,
            "open_self_tasks": self.db.count_open_tasks(
                project_id=self.home_path, pipeline="self"
            ),
            "last_execution": last.isoformat() if last else None,
            "next_eligible": (
                (last + timedelta(days=1)).isoformat() if last else "now"
            ),
            "other_work_active": self.other_work_active(),
            "last_check_result": self._last_result,
            "scheduler_running": self._thread is not None,
        }
