"""Tests for the parallel AnalysisManager batch."""

import os

import pytest

from dcp.agents.status_agent import StatusReportAgent
from dcp.config import Settings
from dcp.cortex import ContextAssembler, StageInferenceEngine
from dcp.cortex.analysis import AnalysisInProgress, AnalysisManager
from dcp.sentry.discovery import ProjectDiscovery


@pytest.fixture
def manager(db):
    return AnalysisManager(
        db,
        StatusReportAgent(Settings(ai_enabled=False)),
        StageInferenceEngine(db),
        ContextAssembler(db),
        max_workers=3,
    )


def registered_paths(db, sample_tree):
    ProjectDiscovery(db).scan(str(sample_tree))
    items, _ = db.list_projects(limit=100)
    return [p.path for p in items]


def test_batch_writes_status_files_everywhere(db, sample_tree, manager):
    paths = registered_paths(db, sample_tree)
    manager.start(paths)
    manager.wait(timeout=30)

    status = manager.status()
    assert status["running"] is False
    assert status["done"] == len(paths)
    assert status["failed"] == 0
    for path in paths:
        report = os.path.join(path, "project_status.md")
        assert os.path.isfile(report)
        content = open(report, encoding="utf-8").read()
        assert "generated by Developer Control Plane" in content


def test_batch_updates_projection_columns(db, sample_tree, manager):
    paths = registered_paths(db, sample_tree)
    manager.start(paths)
    manager.wait(timeout=30)

    items, _ = db.list_projects(limit=100)
    for project in items:
        assert project.status_headline
        assert project.status_health in {"green", "yellow", "red"}
        assert project.analyzed_at


def test_batch_survives_missing_directory(db, sample_tree, manager):
    paths = registered_paths(db, sample_tree)
    ghost = str(sample_tree / "deleted_project")
    manager.start(paths + [ghost])
    manager.wait(timeout=30)

    status = manager.status()
    assert status["failed"] == 1
    assert ghost in status["errors"]
    assert status["done"] == len(paths)  # others unaffected


def test_double_start_rejected(db, sample_tree, manager, monkeypatch):
    import time

    paths = registered_paths(db, sample_tree)

    original = manager.analyze_one
    monkeypatch.setattr(
        manager, "analyze_one",
        lambda p: (time.sleep(0.3), original(p))[1],
    )
    manager.start(paths)
    with pytest.raises(AnalysisInProgress):
        manager.start(paths)
    manager.wait(timeout=30)


def test_batch_logs_inferences_and_decisions(db, sample_tree, manager):
    paths = registered_paths(db, sample_tree)
    manager.start(paths)
    manager.wait(timeout=30)

    inference_types = {i.inference_type for i in db.get_inferences(limit=200)}
    decision_types = {d.decision_type for d in db.get_decisions(limit=200)}
    assert "ProjectStatusReport" in inference_types
    assert "StatusFileWritten" in decision_types
